#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop kaholo-server.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/kaholo-server" ] && [ "$1" = remove ]; then
	invoke-rc.d kaholo-server stop || exit $?
fi
# End automatically added section
